database-type: mysql

host: localhost
port: 3306
database: economy
username: root
password: password

# Uploading eco balance to database. Disabling sync will put less load on the server and database
# But will not update the database on interval.
enable-sync: true
# sync interval in minutes (default: 5)
sync-interval: 5