
database-type: mysql

host: localhost
port: 3306
database: economy
username: root
password: password

# This option allows the data to be uploaded to the database on intervals.
# Disabling this option can cause data loss when server crashes.
enable-sync: true
# sync interval in minutes (default: 30)
sync-interval: 30